name: Test

on:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install pnpm and Node.js
        uses: pnpm/setup@v3
        with:
          version: 12
          runtime: node@24

      - name: Type check
        run: pnpm type-check

      - name: Run unit tests
        run: pnpm test
